### ISSUE TITLE
Maya 2022/SL 2.9.3 errors

### ISSUE THREAD

**Issue by JKG69** [krathjen/studiolibrary#325]
Hi, huge SL fan here, been using and donating for years.  Recently running into some Maya 2022/Python3 probs however.

in Maya 2022/SL2.9.3, when trying to save an anim out, I'm getting this error in a popup dialog box. However, in Maya 2019/SL2.9.3 it works fine.  (the rig is from AdvancedSkeleton. a popular DIY rigging option). 
____________________

Object dict_keys(['FKIndexFinger2_R', 'FKRingFinger3_R', 'FKMiddleFinger2_L', 'IKhybridSpine3_M', 'RootX_M', 'FKIndexFinger3_L', 'FKScapula_R', 'AimEye_M', 'AimEye_L', 'FKIndexFinger1_L', 'AimEye_R', 'FKMiddleFinger1_L', 'IKToes_L', 'FKPinkyFinger2_L', 'FKMiddleFinger2_R', 'FKRingFinger3_L', 'FKIndexFinger2_L', 'FKWrist_R', 'FKMiddleFinger3_R', 'Main', 'FKRingFinger2_L', 'RollToes_L', 'PoleLeg_L', 'FKEye_L', 'FKRingFinger1_R', 'RollHeel_R', 'IKhybridSpine1_M', 'FKRingFinger1_L', 'IKToes_R', 'FKIKSpine_M', 'PoleLeg_R', 'FKEye_R', 'FKRingFinger2_R', 'RollToes_R', 'FKMiddleFinger3_L', 'FKWrist_L', 'FKThumbFinger1_L', 'RollToesEnd_R', 'FKNeck_M', 'FKElbow_L', 'FKIKLeg_R', 'FKHead1_M', 'FKIKArm_L', 'FKPinkyFinger1_R', 'FKIndexFinger3_R', 'FKIKArm_R', 'FKJaw_M', 'Fingers_R', 'FKPinkyFinger2_R', 'IKhybridSpine2_M', 'FKElbow_R', 'RollToesEnd_L', 'IKSpine1_M', 'RollHeel_L', 'IKLeg_L', 'FKPinkyFinger3_R', 'FKCup_L', 'FKIndexFinger1_R', 'FKThumbFinger3_R', 'FKScapula_L', 'FKShoulder_R', 'FKThumbFinger2_L', 'FKShoulder_L', 'FKThumbFinger2_R', 'FKPinkyFinger1_L', 'FKThumbFinger1_R', 'IKSpine3_M', 'FKThumbFinger3_L', 'IKSpine2_M', 'Fingers_L', 'FKCup_R', 'IKLeg_R', 'FKPinkyFinger3_L', 'FKMiddleFinger1_R', 'FKIKLeg_L']) is invalid

In SE stack-trace its a huge long error list for a bunch of skel parts, generally in this format:
Traceback (most recent call last):
  File "C:\Users\Me\Documents\maya\StudioLibrary-2.9.3\src\mutils\attribute.py", line 260, in type
    self._type = maya.cmds.getAttr(self.fullname(), type=True)
TypeError: Object b'FKPinkyFinger3_L'.b'scaleY' is invalid // 
// Error: mutils.attribute : Cannot GET attribute TYPE for "b'FKPinkyFinger3_L'.b'translateZ'"
____________________

Additionally, when attempting in Maya2022/SL2.9.3 to read in an anim from Maya 2019/SL2.7.1 I get this error (in a dialog box): **_'function' object has no attribute 'func_name'_**

while this is what shows up in SE stack trace:

requires "stereoCamera" "10.0";
# File read in  0.17 seconds. # 
// mutils.animation : Loaded: C:/Users/Me/Documents/maya/StudioLibrary/Default/run.anim // 
# Traceback (most recent call last):
#   File "C:\Users\Me\Documents\maya\StudioLibrary-2.9.3\src\studiolibrarymaya\baseloadwidget.py", line 252, in accept
#     self.item().loadFromCurrentValues()
#   File "C:\Users\Me\Documents\maya\StudioLibrary-2.9.3\src\studiolibrarymaya\baseitem.py", line 167, in loadFromCurrentValues
#     self.load(objects=objects, **kwargs)
#   File "C:\Users\Me\Documents\maya\StudioLibrary-2.9.3\src\studiolibrarymaya\animitem.py", line 126, in load
#     currentTime=kwargs.get("currentTime")
#   File "C:\Users\Me\Documents\maya\StudioLibrary-2.9.3\src\mutils\decorators.py", line 44, in wrapped
#     logger.debug('%s function took %0.5f sec' % (fn.func_name, (time2 - time1)))
# AttributeError: 'function' object has no attribute 'func_name'

Again, works fine in  Maya 2019/SL2.7.1

Thanks for your help and your time!

**Comment by krathjen** [comment]
Hi,

Thanks for the information.

I just pushed some changes to the main branch (2.9.4) which will hopefully fix the errors above.

https://github.com/krathjen/studiolibrary

Please let me know how it goes.

Thanks

**Comment by JKG69** [comment]
Thank you for the quick turnaround!

Ok, writing the same pose as last time from M2022/SL2.9.4 now gives this dialog box error:
_'charmap' codec can't decode byte 0x8f in position 4316: character maps to <undefined>


And this trace stack error:
_# Traceback (most recent call last):
#   File "C:\Users\Me\Documents\maya\StudioLibrary-2.9.4\src\studiolibrarymaya\basesavewidget.py", line 435, in accept
#     raise Exception("\n".join(self.formWidget().errors()))
# Exception: No folder selected. Please select a destination folder.
// mutils.transferobject : Saving pose: C:/Users/Me~1/AppData/Local/Temp/StudioLibrary/Me/AnimItem\pose.json // 
// mutils.transferobject : Saved pose: C:/Users/Me~1/AppData/Local/Temp/StudioLibrary/me/AnimItem\pose.json // 
// mutils.animation : Saving animation: C:/Users/Me~1/AppData/Local/Temp/StudioLibrary/me/AnimItem\animation.mb //

Good news however, applying a M2019/2.7.1/2.9.3 animation to M2022/2.9.4 works fine now!

Thanks again for all your hard work! Much appreciated.
